defaultPortal: dummy-theme
portals:
  - name: dummy-theme
    portalId: 26286685
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CLvZ6rPzMBILAAUAAAAAAEwAQAIY3bTEDCDFjbsWKO7pDDIU9VP6D7axRQwueZCqTJbUUpI5vGQ6JgAABEEAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAPABAAABEQhTEV-DEvQrzQfu9l-WuEqyoafmyCUoDZXUxUgBaAA
        expiresAt: '2023-03-31T07:03:42.012Z'
    personalAccessKey: >-
      CiRldTEtZmJjNy01NzJmLTRhYTQtYjEyNy02ODdlNDQxNzlhZjQQ3bTEDBjFjbsWKhkABeaRgqhPDgLcx5gbToBZf1ZoBfdA6nfrSgNldTE
    sandboxAccountType: null
    parentAccountId: null
